### ISSUE TITLE
Manual dag facts, for safe keeping

### ISSUE THREAD

**Issue by mgwalker** [18F/18f-bot-facts#12]

**Comment by mgwalker** [comment]
> Darla (my sister's dog) is obsessed with lights of any kind, so she licks people's phones to get them to light up
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C035CQWNA/p1553875698001900)</sub>

**Comment by mgwalker** [comment]
> Sidney really only plays with dogs whose ears stand up like hers. She is very suspicious of dogs who have floppy ears. It took me a few years to realize this and only became super evident when she would barely acknowledge the neighbors bloodhound.
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C035CQWNA/p1553878192005700)</sub>

**Comment by mgwalker** [comment]
> Winry doesn't understand pointing with your hands, but she _does_ understand pointing with your feet. But she'll look at you unhappily if there's no food where you're foot-pointing.
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C035CQWNA/p1562777514215500)</sub>

**Comment by mgwalker** [comment]
@tbaxter-18f Hover over a message, click the `...` button, and there should be an option for `Comment on Issue or PR Github`. If not, you may need to link your Slack and Github with `/github signin`. Anyway, once you click that option, it'll pop up a thing you can use to search repos/issues/PRs to add the comment to.

**Comment by tbaxter-18f** [comment]
> Manual dag fact: :cooper: Cooper will not eat peanuts or peanut butter.
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C035CQWNA/p1562697732207600)</sub>

**Comment by tbaxter-18f** [comment]
> :belle-belle: fact: Belle knows such esoteric commands/requests as:
- `snorkle!` - crawl out at least far enough from under covers to stick your nose out because you’re overheating
- `off the bed, please` - the “please” is an integral part of that request and she doesn’t think you’re serious until you include it)
- `come be friends` - come snuggle or lay next to me
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C035CQWNA/p1564404112028000)</sub>

**Comment by tbaxter-18f** [comment]
> Also... Cooper doesn't really understand "Staining the deck", so he stuck his face between two balusters and now has dark brown stripes on either side of his head. :disappointed:
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C035CQWNA/p1556629972010800)</sub>

**Comment by tbaxter-18f** [comment]
> manual dag fact: :cupcake-dag: Cupcake often sits on my shoulders
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C10EGE62W/p1555681964389400)</sub>

**Comment by tbaxter-18f** [comment]
> manual dag fact: :cupcake-dag: Cupcake often sits on my shoulders
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C10EGE62W/p1555681964389400)</sub>

**Comment by mgwalker** [comment]
> Belle once ate an entire bag of green candy melts and had green :poop: for a couple days
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C035CQWNA/p1568979735026200)</sub>
