### ISSUE TITLE
Add Minnesota facts

### ISSUE THREAD

**Issue by gboone** [18F/18f-bot-facts#18]
Happy to help prepare this PR. Opening an issue so I don't forget and the good people at 18F can hold me accountable and let me know if I miss anything. I think all we need is a JSON file to contain facts about The Greatest State in the Union: Minnesota. 

Similar to #12 this issue can also be a placeholder for important facts we shouldn't forget.

This would include things like:

> Contrary to what you may have heard, Minnesota has _more_ than 10,000 lakes.

> Prince lived here. Yes, that Prince.

> Unlike it's neighbor to the east, Minnesota has standards for how large a body of water must be in order to qualify as a lake.

> The Twins haven't won a World Series since 1991 but it's OK because none of Minnesota's neighbor states have even won a pennant.

> Minnesota has more coastline than California and Hawaii combined.

> Some people say the state bird is the mosquito but that's actually DC's state bird. Minnesota's is the Common Loon.

> Bob Dylan was born in Minnesota.

> Duluth Pack and Duluth Trading Company are different companies.

etc. Paging @pkarman @awfrancisco for assistance

**Comment by randyhart** [comment]
@gboone I took care of this for you all.
